backend:
  name: git-gateway
  branch: main
media_folder: "_site/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "vehicles"
    label: "Vehicles"
    folder: "vehicles"
    create: true
    slug: "{{vin}}"
    editor:
      preview: false
    fields:
      - {label: "Layout", name: "layout", widget: hidden, default: "layouts/vehicle.html"}
      - {label: "Vehicle Name", name: "name", widget: "string" }
      - {label: "Price", name: "Price", widget: "number", value_type: "float"}
      - {label: "Vin", name: "vin", widget: "string" }
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Drivetrain", name: "drivetrain", widget: "string"}
      - {label: "Body Style", name: "body-style", widget: "string"}
      - {label: "Color", name: "color", widget: "string"}
      - {label: "Model", name: "model", widget: "string"}
      - {label: "Kilometres", name: "kilometres", widget: "number"}
      - {label: "Seats", name: "seats", widget: "number"}
      - {label: "Condition", name: "condition", widget: "select", options: ["Used", "New"]}
      - {label: "Transmission", name: "transmission", widget: "select", options: ["Automatic", "Manual"]}
      - {label: "Fuel", name: "fuel", widget: "select", options: ["Gas", "Diesel"]}
      - {label: "Images", name: "images", widget: "list", summary: "{{fields.image}}", field: {label: Image, name: image, widget: image}}

      
